<?php

/*
 * Stap 0
 * Vocabularies, vocabulary term values en content-types.
 *
 * In install-file.
 * Feature clio_indicators_and_countries bevat vocabularies,
 * clio_datapoint_and_data_views bevat o.a. content-type datapoint
 */

// Clio Infra will show data from 1500 to this year.
define('CLIO_MAX_YEAR', 2013);
// The maximum value from a CSV allowed in the database.
define('CLIO_MAX_VALUE', 32000);
// This will be replaced by the maximum value.
define('CLIO_VALUE_REPLACE', 'hyperinflation');
// CSV delimiter.
define('CLIO_DELIMITER', ',');



/**
 * Implements hook_menu().
 *
 * Creates a 'Clio Infra' section on the administration page for Clio
 * modules to use for their configuration and settings.
 */
function clio_menu() {
  $items['home'] = array(
    'title' => 'Clio Infra',
    'page callback' => 'clio_home',
    'access arguments' => array('access content'),
  );
  $items['admin/config/clio'] = array(
    'title' => 'Clio Infra',
    'description' => 'Settings for Clio Infra modules.',
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  return $items;
}


/*
 * A completely empty home page, suitable to add blocks.
 */
function clio_home() {
  return '';
}


/*
 * Get a list of all countries known in the system.
 *
 * @return $countries
 *   An array keyed by country ID (the numerical id).
 * TODO cache
 */
function clio_get_countries() {
  $countries_vocab = taxonomy_vocabulary_machine_name_load('countries');
  $countries_tree = taxonomy_get_tree($countries_vocab->vid, 0, NULL, TRUE);
  $countries = array();
  foreach ($countries_tree as $country) {
    if (!empty($country->field_country_id)) {
      $country_id = $country->field_country_id['und'][0]['value'];
      $country_code = !empty($country->field_country_code) ? $country->field_country_code['und'][0]['value'] : '';
      $countries[$country_id] = array('name' => $country->name, 'tid' => $country->tid, 'code' => $country_code);
    }
  }
  return $countries;
}

