insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (4, 'Afghanistan', 'Afghanistan', 'AFG', 1, '34');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (8, 'Albania', 'Albania', 'ALB', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (12, 'Algeria', 'Algeria', 'DZA', 1, '15');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (20, 'Andorra', 'Andorra', 'AND', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (24, 'Angola', 'Angola', 'AGO', 1, '17');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (660, 'Anguilla', 'Anguilla', 'AIA', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (28, 'Antigua and Barbuda', 'Antigua and Barbuda', 'ATG', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (32, 'Argentina', 'Argentina', 'ARG', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (51, 'Armenia', 'Armenia', 'ARM', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (533, 'Aruba', 'Aruba', 'ABW', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (36, 'Australia', 'Australia', 'AUS', 1, '53');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (40, 'Austria', 'Austria', 'AUT', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (31, 'Azerbaijan', 'Azerbaijan', 'AZE', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (44, 'Bahamas', 'Bahamas', 'BHS', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (48, 'Bahrain', 'Bahrain', 'BHR', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (50, 'Bangladesh', 'Bangladesh', 'BGD', 1, '34');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (52, 'Barbados', 'Barbados', 'BRB', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (112, 'Belarus', 'Belarus', 'BLR', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (56, 'Belgium', 'Belgium', 'BEL', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (84, 'Belize', 'Belize', 'BLZ', 1, '13');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (204, 'Benin', 'Benin', 'BEN', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (60, 'Bermuda', 'Bermuda', 'BMU', 1, '21');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (64, 'Bhutan', 'Bhutan', 'BTN', 1, '34');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (70, 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BIH', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (72, 'Botswana', 'Botswana', 'BWA', 1, '18');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (76, 'Brazil', 'Brazil', 'BRA', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (92, 'British Virgin Islands', 'British Virgin Islands', 'VGB', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (96, 'Brunei Darussalam', 'Brunei Darussalam', 'BRN', 1, '35');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (100, 'Bulgaria', 'Bulgaria', 'BGR', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (854, 'Burkina Faso', 'Burkina Faso', 'BFA', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (108, 'Burundi', 'Burundi', 'BDI', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (116, 'Cambodia', 'Cambodia', 'KHM', 1, '35');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (120, 'Cameroon', 'Cameroon', 'CMR', 1, '17');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (124, 'Canada', 'Canada', 'CAN', 1, '21');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (132, 'Cape Verde', 'Cape Verde', 'CPV', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (136, 'Cayman Islands', 'Cayman Islands', 'CYM', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (148, 'Chad', 'Chad', 'TCD', 1, '17');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (152, 'Chile', 'Chile', 'CHL', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (156, 'China', 'China', 'CHN', 1, '30');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (170, 'Colombia', 'Colombia', 'COL', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (174, 'Comoros', 'Comoros', 'COM', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (178, 'Congo', 'Congo', 'COG', 1, '17');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (184, 'Cook Islands', 'Cook Islands', 'COK', 1, '61');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (188, 'Costa Rica', 'Costa Rica', 'CRI', 1, '13');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (191, 'Croatia', 'Croatia', 'HRV', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (192, 'Cuba', 'Cuba', 'CUB', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (196, 'Cyprus', 'Cyprus', 'CYP', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (203, 'Czech Republic', 'Czech Republic', 'CZE', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (208, 'Denmark', 'Denmark', 'DNK', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (262, 'Djibouti', 'Djibouti', 'DJI', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (212, 'Dominica', 'Dominica', 'DMA', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (214, 'Dominican Republic', 'Dominican Republic', 'DOM', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (218, 'Ecuador', 'Ecuador', 'ECU', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (818, 'Egypt', 'Egypt', 'EGY', 1, '15');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (222, 'El Salvador', 'El Salvador', 'SLV', 1, '13');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (226, 'Equatorial Guinea', 'Equatorial Guinea', 'GNQ', 1, '17');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (232, 'Eritrea', 'Eritrea', 'ERI', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (233, 'Estonia', 'Estonia', 'EST', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (242, 'Fiji', 'Fiji', 'FJI', 1, '54');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (246, 'Finland', 'Finland', 'FIN', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (250, 'France', 'France', 'FRA', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (254, 'French Guiana', 'French Guiana', 'GUF', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (266, 'Gabon', 'Gabon', 'GAB', 1, '17');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (270, 'Gambia', 'Gambia', 'GMB', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (268, 'Georgia', 'Georgia', 'GEO', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (276, 'Germany', 'Germany', 'DEU', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (288, 'Ghana', 'Ghana', 'GHA', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (292, 'Gibraltar', 'Gibraltar', 'GIB', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (300, 'Greece', 'Greece', 'GRC', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (304, 'Greenland', 'Greenland', 'GRL', 1, '21');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (308, 'Grenada', 'Grenada', 'GRD', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (320, 'Guatemala', 'Guatemala', 'GTM', 1, '13');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (831, 'Guernsey', 'Guernsey', 'GGY', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (324, 'Guinea', 'Guinea', 'GIN', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (624, 'Guinea-Bissau', 'Guinea-Bissau', 'GNB', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (328, 'Guyana', 'Guyana', 'GUY', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (332, 'Haiti', 'Haiti', 'HTI', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (336, 'Holy See', 'Holy See', 'VAT', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (340, 'Honduras', 'Honduras', 'HND', 1, '13');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (348, 'Hungary', 'Hungary', 'HUN', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (352, 'Iceland', 'Iceland', 'ISL', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (356, 'India', 'India', 'IND', 1, '34');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (360, 'Indonesia', 'Indonesia', 'IDN', 1, '35');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (368, 'Iraq', 'Iraq', 'IRQ', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (372, 'Ireland', 'Ireland', 'IRL', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (833, 'Isle of Man', 'Isle of Man', 'IMN', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (376, 'Israel', 'Israel', 'ISR', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (380, 'Italy', 'Italy', 'ITA', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (388, 'Jamaica', 'Jamaica', 'JAM', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (392, 'Japan', 'Japan', 'JPN', 1, '30');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (832, 'Jersey', 'Jersey', 'JEY', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (400, 'Jordan', 'Jordan', 'JOR', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (398, 'Kazakhstan', 'Kazakhstan', 'KAZ', 1, '143');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (404, 'Kenya', 'Kenya', 'KEN', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (296, 'Kiribati', 'Kiribati', 'KIR', 1, '57');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (414, 'Kuwait', 'Kuwait', 'KWT', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (417, 'Kyrgyzstan', 'Kyrgyzstan', 'KGZ', 1, '143');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (428, 'Latvia', 'Latvia', 'LVA', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (422, 'Lebanon', 'Lebanon', 'LBN', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (426, 'Lesotho', 'Lesotho', 'LSO', 1, '18');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (430, 'Liberia', 'Liberia', 'LBR', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (438, 'Liechtenstein', 'Liechtenstein', 'LIE', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (440, 'Lithuania', 'Lithuania', 'LTU', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (442, 'Luxembourg', 'Luxembourg', 'LUX', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (450, 'Madagascar', 'Madagascar', 'MDG', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (454, 'Malawi', 'Malawi', 'MWI', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (458, 'Malaysia', 'Malaysia', 'MYS', 1, '35');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (462, 'Maldives', 'Maldives', 'MDV', 1, '34');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (466, 'Mali', 'Mali', 'MLI', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (470, 'Malta', 'Malta', 'MLT', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (584, 'Marshall Islands', 'Marshall Islands', 'MHL', 1, '57');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (478, 'Mauritania', 'Mauritania', 'MRT', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (480, 'Mauritius', 'Mauritius', 'MUS', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (484, 'Mexico', 'Mexico', 'MEX', 1, '13');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (583, 'Micronesia (Federated States of)', 'Micronesia (Federated States of)', 'FSM', 1, '57');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (492, 'Monaco', 'Monaco', 'MCO', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (496, 'Mongolia', 'Mongolia', 'MNG', 1, '30');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (499, 'Montenegro', 'Montenegro', 'MNE', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (500, 'Montserrat', 'Montserrat', 'MSR', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (504, 'Morocco', 'Morocco', 'MAR', 1, '15');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (508, 'Mozambique', 'Mozambique', 'MOZ', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (516, 'Namibia', 'Namibia', 'NAM', 1, '18');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (520, 'Nauru', 'Nauru', 'NRU', 1, '57');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (524, 'Nepal', 'Nepal', 'NPL', 1, '34');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (528, 'Netherlands', 'Netherlands', 'NLD', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (554, 'New Zealand', 'New Zealand', 'NZL', 1, '53');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (558, 'Nicaragua', 'Nicaragua', 'NIC', 1, '13');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (562, 'Niger', 'Niger', 'NER', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (566, 'Nigeria', 'Nigeria', 'NGA', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (570, 'Niue', 'Niue', 'NIU', 1, '61');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (578, 'Norway', 'Norway', 'NOR', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (512, 'Oman', 'Oman', 'OMN', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (586, 'Pakistan', 'Pakistan', 'PAK', 1, '34');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (585, 'Palau', 'Palau', 'PLW', 1, '57');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (591, 'Panama', 'Panama', 'PAN', 1, '13');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (598, 'Papua New Guinea', 'Papua New Guinea', 'PNG', 1, '54');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (600, 'Paraguay', 'Paraguay', 'PRY', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (604, 'Peru', 'Peru', 'PER', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (608, 'Philippines', 'Philippines', 'PHL', 1, '35');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (616, 'Poland', 'Poland', 'POL', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (620, 'Portugal', 'Portugal', 'PRT', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (630, 'Puerto Rico', 'Puerto Rico', 'PRI', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (634, 'Qatar', 'Qatar', 'QAT', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (642, 'Romania', 'Romania', 'ROU', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (643, 'Russian Federation', 'Russian Federation', 'RUS', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (646, 'Rwanda', 'Rwanda', 'RWA', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (659, 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'KNA', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (662, 'Saint Lucia', 'Saint Lucia', 'LCA', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (670, 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VCT', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (882, 'Samoa', 'Samoa', 'WSM', 1, '61');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (674, 'San Marino', 'San Marino', 'SMR', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (682, 'Saudi Arabia', 'Saudi Arabia', 'SAU', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (686, 'Senegal', 'Senegal', 'SEN', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (688, 'Serbia', 'Serbia', 'SRB', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (690, 'Seychelles', 'Seychelles', 'SYC', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (694, 'Sierra Leone', 'Sierra Leone', 'SLE', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (702, 'Singapore', 'Singapore', 'SGP', 1, '35');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (703, 'Slovakia', 'Slovakia', 'SVK', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (705, 'Slovenia', 'Slovenia', 'SVN', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (90, 'Solomon Islands', 'Solomon Islands', 'SLB', 1, '54');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (706, 'Somalia', 'Somalia', 'SOM', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (710, 'South Africa', 'South Africa', 'ZAF', 1, '18');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (724, 'Spain', 'Spain', 'ESP', 1, '39');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (144, 'Sri Lanka', 'Sri Lanka', 'LKA', 1, '34');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (740, 'Suriname', 'Suriname', 'SUR', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (748, 'Swaziland', 'Swaziland', 'SWZ', 1, '18');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (752, 'Sweden', 'Sweden', 'SWE', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (756, 'Switzerland', 'Switzerland', 'CHE', 1, '155');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (760, 'Syrian Arab Republic', 'Syrian Arab Republic', 'SYR', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (762, 'Tajikistan', 'Tajikistan', 'TJK', 1, '143');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (764, 'Thailand', 'Thailand', 'THA', 1, '35');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (626, 'Timor-Leste', 'Timor-Leste', 'TLS', 1, '35');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (768, 'Togo', 'Togo', 'TGO', 1, '11');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (772, 'Tokelau', 'Tokelau', 'TKL', 1, '61');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (776, 'Tonga', 'Tonga', 'TON', 1, '61');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (780, 'Trinidad and Tobago', 'Trinidad and Tobago', 'TTO', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (788, 'Tunisia', 'Tunisia', 'TUN', 1, '15');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (792, 'Turkey', 'Turkey', 'TUR', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (795, 'Turkmenistan', 'Turkmenistan', 'TKM', 1, '143');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (796, 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'TCA', 1, '29');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (798, 'Tuvalu', 'Tuvalu', 'TUV', 1, '61');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (800, 'Uganda', 'Uganda', 'UGA', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (804, 'Ukraine', 'Ukraine', 'UKR', 1, '151');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (784, 'United Arab Emirates', 'United Arab Emirates', 'ARE', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (826, 'United Kingdom of Great Britain and Northern Ireland', 'United Kingdom of Great Britain and Northern Ireland', 'GBR', 1, '154');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (840, 'United States of America', 'United States of America', 'USA', 1, '21');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (858, 'Uruguay', 'Uruguay', 'URY', 1, '5');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (860, 'Uzbekistan', 'Uzbekistan', 'UZB', 1, '143');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (548, 'Vanuatu', 'Vanuatu', 'VUT', 1, '54');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (732, 'Western Sahara', 'Western Sahara', 'ESH', 1, '15');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (887, 'Yemen', 'Yemen', 'YEM', 1, '145');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (894, 'Zambia', 'Zambia', 'ZMB', 1, '14');
insert into countries (country_id, country_name, country_description, country_code, active, region_id) values (716, 'Zimbabwe', 'Zimbabwe', 'ZWE', 1, '14');
