INSERT into regions (region_id, region_name, region_description, region_root) values (11, 'Western Africa', 'Western Africa', 2);
INSERT into regions (region_id, region_name, region_description, region_root) values (13, 'Central America', 'Central America', 19);
INSERT into regions (region_id, region_name, region_description, region_root) values (14, 'Eastern Africa', 'Eastern Africa', 2);
INSERT into regions (region_id, region_name, region_description, region_root) values (142, 'Asia', 'Asia', 0);
INSERT into regions (region_id, region_name, region_description, region_root) values (143, 'Central Asia', 'Central Asia', 142);
INSERT into regions (region_id, region_name, region_description, region_root) values (145, 'Western Asia', 'Western Asia', 142);
INSERT into regions (region_id, region_name, region_description, region_root) values (15, 'Northern Africa', 'Northern Africa', 2);
INSERT into regions (region_id, region_name, region_description, region_root) values (150, 'Europe', 'Europe', 0);
INSERT into regions (region_id, region_name, region_description, region_root) values (151, 'Eastern Europe', 'Eastern Europe', 150);
INSERT into regions (region_id, region_name, region_description, region_root) values (154, 'Northern Europe', 'Northern Europe', 150);
INSERT into regions (region_id, region_name, region_description, region_root) values (155, 'Western Europe', 'Western Europe', 150);
INSERT into regions (region_id, region_name, region_description, region_root) values (17, 'Middle Africa', 'Middle Africa', 2);
INSERT into regions (region_id, region_name, region_description, region_root) values (18, 'Southern Africa', 'Southern Africa', 2);
INSERT into regions (region_id, region_name, region_description, region_root) values (19, 'Americas', 'Americas', 0);
INSERT into regions (region_id, region_name, region_description, region_root) values (2, 'Africa', 'Africa', 0);
INSERT into regions (region_id, region_name, region_description, region_root) values (21, 'Northern America', 'Northern America', 19);
INSERT into regions (region_id, region_name, region_description, region_root) values (29, 'Caribbean', 'Caribbean', 19);
INSERT into regions (region_id, region_name, region_description, region_root) values (30, 'Eastern Asia', 'Eastern Asia', 142);
INSERT into regions (region_id, region_name, region_description, region_root) values (34, 'Southern Asia', 'Southern Asia', 142);
INSERT into regions (region_id, region_name, region_description, region_root) values (35, 'South-Eastern Asia', 'South-Eastern Asia', 142);
INSERT into regions (region_id, region_name, region_description, region_root) values (39, 'Southern Europe', 'Southern Europe', 150);
INSERT into regions (region_id, region_name, region_description, region_root) values (419, 'Latin America and the Caribbean', 'Latin America and the Caribbean', 19);
INSERT into regions (region_id, region_name, region_description, region_root) values (5, 'South America', 'South America', 19);
INSERT into regions (region_id, region_name, region_description, region_root) values (53, 'Australia and New Zealand', 'Australia and New Zealand', 9);
INSERT into regions (region_id, region_name, region_description, region_root) values (54, 'Melanesia', 'Melanesia', 9);
INSERT into regions (region_id, region_name, region_description, region_root) values (57, 'Micronesia', 'Micronesia', 9);
INSERT into regions (region_id, region_name, region_description, region_root) values (61, 'Polynesia', 'Polynesia', 9);
INSERT into regions (region_id, region_name, region_description, region_root) values (9, 'Oceania', 'Oceania', 0);
